import i18n from "i18next";
import { initReactI18next} from "react-i18next";

i18n.use(initReactI18next).init({
    debug:false,
    fallbackLng:'fr',
    resources:{
        fr: {
            translation: {
                //Backend response
                'backend.admin.incorect.query.params' : 'Paramètres de requête incorrects',
                'backend.admin.invalid.page.size' : 'Page et taille invalides',
                'backend.admin.invalid.sorting.params' : 'Parametres de tri invalides',
                'backend.admin.invalid.user.id' : 'Identifiant utilisateur invalide',
                'backend.admin.user.not.found' : 'Utilisateur introuvable',
                'backend.admin.delete.self.forbidden' : 'Vous ne pouvez pas vous supprimer vous-meme',
                'backend.admin.delete.success' : 'Utilisateur supprime avec succes',
                'backend.admin.change.own.role.forbidden' : 'Vous ne pouvez pas modifier votre propre role',
                'backend.admin.role.required' : 'Le role est requis',

                'backend.auth.duplicate.user' : 'Un utilisateur avec cet email ou ce nom existe deja',
                'backend.auth.invalid.credentials' : 'Identifiants incorrects',
                'backend.auth.logout.success' : 'Deconnexion reussie',
                'backend.auth.no.user.after.authentication' : 'Aucun utilisateur trouve apres authentification',
                'backend.auth.no.valid.token' : 'Token invalide',
                'backend.auth.token.missing' : 'Acces refuse: token manquant',
                'backend.auth.token.invalid.or.expired' : 'Token invalide ou expire',
                'backend.auth.user.not.found' : 'Utilisateur introuvable',
                'backend.auth.server.error' : 'Erreur serveur pendant l authentification',
                'backend.auth.refresh.token.invalid' : 'Refresh token invalide',
                'backend.auth.refresh.token.revoked' : 'Refresh token revoque',

                'backend.profile.no.user.after.authentication' : 'Aucun utilisateur trouve apres authentification',
                'backend.profile.invalid.user.id' : 'Identifiant utilisateur invalide',
                'backend.profile.user.not.found' : 'Utilisateur introuvable',
                'backend.profile.incorrect.credentials' : 'Identifiants incorrects',
                'backend.profile.password.updated' : 'Mot de passe mis a jour avec succes',
                'backend.profile.no.file.uploaded' : 'Aucun fichier televerse',
                'backend.profile.avatar.uploaded' : 'Avatar televerse avec succes',
                'backend.profile.search.query.too.short' : 'La recherche doit contenir au moins 2 caracteres',

                'backend.friends.no.user.after.authentication' : 'Aucun utilisateur trouve apres authentification',
                'backend.friends.cannot.add.yourself' : 'Vous ne pouvez pas vous ajouter vous-meme',
                'backend.friends.already.friends' : 'Vous etes deja amis',
                'backend.friends.request.already.pending' : 'Une demande est deja en attente',
                'backend.friends.blocked.by.you' : 'Vous avez bloque cet utilisateur',
                'backend.friends.blocked.you' : 'Cet utilisateur vous a bloque',
                'backend.friends.unable.to.send.request' : 'Impossible d envoyer la demande',
                'backend.friends.invalid.request.id' : 'Identifiant de demande invalide',
                'backend.friends.request.not.found' : 'Demande d ami introuvable',
                'backend.friends.not.authorized' : 'Non autorise',
                'backend.friends.internal.error' : 'Erreur interne',
                'backend.friends.only.receiver.can.accept' : 'Seul le receveur peut accepter',
                'backend.friends.only.receiver.can.reject' : 'Seul le receveur peut refuser',
                'backend.friends.only.sender.can.cancel' : 'Seul l expediteur peut annuler',
                'backend.friends.request.not.pending' : 'La demande n est pas en attente',
                'backend.friends.invalid.action' : 'Action invalide',
                'backend.friends.not.friends' : 'Vous n etes pas amis',
                'backend.friends.unfriended' : 'Amitie supprimee',

                'backend.middleware.role.unauthorized' : 'Non authentifie',
                'backend.middleware.role.forbidden' : 'Acces interdit',
                'backend.middleware.upload.not.image' : 'Fichier image requis',
                'backend.middleware.upload.image.processing.error' : 'Erreur lors du traitement de l image',

                'backend.common.internal.server.error' : 'Erreur interne du serveur',

                //navbar
                'navbar.home' : 'Accueil',
                'navbar.pong' : 'PingPong',
                'navbar.scoreboard' : 'Scores',
                'navbar.chat' : 'Messagerie',
                'navbar.profile' : 'Profile',
                'navbar.admin' : 'Admin',
                'navbar.login' : 'Connexion',
                'navbar.register' : 'Inscription',

                //HomePage
                'homepage.home' : 'Bienvenue sur notre transcendence',

                //types
                'types.connexion.email' : 'Email invalide',
                'types.connexion.mdp' : 'Mot dq invalide',
                'types.min.3' : 'Ne peux contenir moins de 3 caracteres',
                'types.max.24' : 'Ne peux contenir plus de 24 caracteres',
                'types.allowed_chars' : 'Caracteres autorises: lettres, chiffres, - et _',
                'types.email' : 'Email valide requis',
                'types.min.10' : 'Ne peux contenir moins de 10 caracteres',
                'types.mdp.char' : 'Doit contenir minuscule, majuscule, chiffre et caractere special',
                'types.mdp.allow' : 'Caracteres speciaux autorises: !@#$%&*()_-+=',
                'types.inscription.mdp.similar' : 'Les mots de passes doivent etre similaires',

                //Admin
                'admin.common.loading': 'Chargement...',
                'admin.header.title': 'Espace administrateur',
                'admin.header.subtitle': 'Gestion des comptes utilisateurs et des droits.',
                'admin.create.title': 'Creer un utilisateur',
                'admin.create.subtitle': 'Renseigne les informations ci-dessous pour ajouter un nouveau compte.',
                'admin.searchPlaceholder': 'Recherche par username, email ou id',
                'admin.list.usersCount': 'Utilisateurs ({{count}})',
                'admin.list.page': 'Page {{page}}/{{totalPages}}',
                'admin.emptyState': 'Selectionne un utilisateur dans la liste pour voir les details.',
                'admin.form.username': 'Username',
                'admin.form.email': 'Email',
                'admin.form.password': 'Mot de passe',
                'admin.form.newPassword': 'Nouveau mot de passe',
                'admin.form.passwordPlaceholder': 'Laisser vide pour ne pas changer',
                'admin.form.avatar': 'Avatar',
                'admin.role.title': 'Role utilisateur',
                'admin.delete.title': 'Zone sensible',
                'admin.delete.confirmMessage': 'Supprimer {{username}} ? Cette action est irreversible.',
                'admin.actions.search': 'Rechercher',
                'admin.actions.refresh': 'Rafraichir',
                'admin.actions.previous': 'Precedent',
                'admin.actions.next': 'Suivant',
                'admin.actions.createUser': 'Creer l utilisateur',
                'admin.actions.saveChanges': 'Sauvegarder les changements',
                'admin.actions.updateRole': 'Mettre a jour le role',
                'admin.actions.deleteUser': 'Supprimer cet utilisateur',
                'admin.actions.confirm': 'Confirmer',
                'admin.actions.cancel': 'Annuler',
                'admin.sort.createdAt': 'Date creation',
                'admin.sort.username': 'Username',
                'admin.sort.email': 'Email',
                'admin.sort.role': 'Role',
                'admin.sort.status': 'Statut',
                'admin.sort.desc': 'DESC',
                'admin.sort.asc': 'ASC',
                'admin.roles.USER': 'Utilisateur',
                'admin.roles.ADMIN': 'Administrateur',
                'admin.status.online': 'EN LIGNE',
                'admin.status.offline': 'HORS LIGNE',
                'admin.editor.title': 'Edition {{username}}',
                'admin.feedback.loadError': 'Erreur lors du chargement des utilisateurs',
                'admin.feedback.unexpectedLoadError': 'Erreur inattendue lors du chargement des utilisateurs',
                'admin.feedback.createSuccess': 'Utilisateur cree avec succes',
                'admin.feedback.createError': 'Echec de la creation utilisateur',
                'admin.feedback.unexpectedCreateError': 'Erreur inattendue lors de la creation utilisateur',
                'admin.feedback.updateSuccess': 'Utilisateur mis a jour avec succes',
                'admin.feedback.updateError': 'Echec de la mise a jour utilisateur',
                'admin.feedback.unexpectedUpdateError': 'Erreur inattendue lors de la mise a jour utilisateur',
                'admin.feedback.roleUpdateSuccess': 'Role mis a jour avec succes',
                'admin.feedback.roleUpdateError': 'Echec de la mise a jour du role',
                'admin.feedback.unexpectedRoleUpdateError': 'Erreur inattendue lors de la mise a jour du role',
                'admin.feedback.deleteSuccess': 'Utilisateur supprime avec succes',
                'admin.feedback.deleteError': 'Echec de suppression utilisateur',
                'admin.feedback.unexpectedDeleteError': 'Erreur inattendue lors de la suppression utilisateur',
                'admin.validation.invalidEmail': 'Email invalide',
                'admin.validation.usernameMin': 'Ne peux contenir moins de 3 caracteres',
                'admin.validation.usernameMax': 'Ne peux contenir plus de 24 caracteres',
                'admin.validation.usernamePattern': 'Caracteres autorises: lettres, chiffres, - et _',
                'admin.validation.passwordMin': 'Ne peux contenir moins de 8 caracteres',
                'admin.validation.passwordPattern': 'Doit contenir minuscule, majuscule, chiffre et caractere special',
                'admin.validation.passwordSpecialChars': 'Caracteres speciaux autorises: !@#$%&*()_-+=',
                'admin.validation.string': 'Entrée invalide : chaîne de caractères attendue, valeur indéfinie reçue',
                //messagerie
                
                //profile
                'profile.modifier' : 'Modifier',
                'profile.deconnecion' : 'Deconnexion',
                'profile.datecreate' : 'Date de creation',
                'profile.actuelmdp' : 'Mot de pass actuel',
                'profile.newmdp' : 'Nouveau mot de passe',
                'profile.save' : 'Sauvegarder',
                'profile.annule' : 'Annuler',
                'profile.delete' : 'Supprimer l ami',
                'profile.add' : 'Ajouter en ami',
                'profile.pending' : 'Demande en attente',
                'profile.notification' : 'Notifications',
                'profile.newMessage' : 'Nouveaux messages',
                'profile.friendRequest' : 'Demande d amis',
                'profile.search' : 'Recherche',

                'profile.opponent' : 'Adversaire',
                'profile.result' : 'Resultat',
                'profile.score' : 'Score',
                'profile.time' : 'Duree',
                'profile.date' : 'Date',
            
                'profile.err.data' : 'Nom d utilisateur ou email déjà utilise',
                'profile.err.wrongPassword' : 'Le mot de passe ne correspond pas au mot de passe actuel',
                'profile.err.avatar' : 'Erreur lors du chargement de l image',

                //chat
                'chat.send' : 'Envoyer',
                'chat.yourMsg' : 'votre message',
                'chat.longMsg' : 'Votre message est trop long',
                'chat.moderation' : 'Votre message n est pas approprie'
            }
        },
        en: {
            translation: {
                //Backend response
                'backend.admin.incorect.query.params' : 'Incorrect query parameters',
                'backend.admin.invalid.page.size' : 'Invalid page and size values',
                'backend.admin.invalid.sorting.params' : 'Invalid sorting parameters',
                'backend.admin.invalid.user.id' : 'Invalid user id',
                'backend.admin.user.not.found' : 'User not found',
                'backend.admin.delete.self.forbidden' : 'You cannot delete your own account',
                'backend.admin.delete.success' : 'User deleted successfully',
                'backend.admin.change.own.role.forbidden' : 'You cannot change your own role',
                'backend.admin.role.required' : 'Role is required',

                'backend.auth.duplicate.user' : 'A user with this email or username already exists',
                'backend.auth.invalid.credentials' : 'Incorrect credentials',
                'backend.auth.logout.success' : 'Logged out successfully',
                'backend.auth.no.user.after.authentication' : 'No user found after authentication',
                'backend.auth.no.valid.token' : 'No valid token',
                'backend.auth.token.missing' : 'Access denied: token missing',
                'backend.auth.token.invalid.or.expired' : 'Invalid or expired token',
                'backend.auth.user.not.found' : 'User not found',
                'backend.auth.server.error' : 'Server error during authentication',
                'backend.auth.refresh.token.invalid' : 'Invalid refresh token',
                'backend.auth.refresh.token.revoked' : 'Refresh token revoked',

                'backend.profile.no.user.after.authentication' : 'No user found after authentication',
                'backend.profile.invalid.user.id' : 'Invalid user id',
                'backend.profile.user.not.found' : 'User not found',
                'backend.profile.incorrect.credentials' : 'Incorrect credentials',
                'backend.profile.password.updated' : 'Password updated successfully',
                'backend.profile.no.file.uploaded' : 'No file uploaded',
                'backend.profile.avatar.uploaded' : 'Avatar uploaded successfully',
                'backend.profile.search.query.too.short' : 'Search query must contain at least 2 characters',

                'backend.friends.no.user.after.authentication' : 'No user found after authentication',
                'backend.friends.cannot.add.yourself' : 'You cannot add yourself',
                'backend.friends.already.friends' : 'You are already friends',
                'backend.friends.request.already.pending' : 'A friend request is already pending',
                'backend.friends.blocked.by.you' : 'You have blocked this user',
                'backend.friends.blocked.you' : 'You are blocked by this user',
                'backend.friends.unable.to.send.request' : 'Unable to send request',
                'backend.friends.invalid.request.id' : 'Invalid request id',
                'backend.friends.request.not.found' : 'Friend request not found',
                'backend.friends.not.authorized' : 'Not authorized',
                'backend.friends.internal.error' : 'Internal error',
                'backend.friends.only.receiver.can.accept' : 'Only receiver can accept',
                'backend.friends.only.receiver.can.reject' : 'Only receiver can reject',
                'backend.friends.only.sender.can.cancel' : 'Only sender can cancel',
                'backend.friends.request.not.pending' : 'Request is not pending',
                'backend.friends.invalid.action' : 'Invalid action',
                'backend.friends.not.friends' : 'Not friends',
                'backend.friends.unfriended' : 'Unfriended',

                'backend.middleware.role.unauthorized' : 'Unauthorized',
                'backend.middleware.role.forbidden' : 'Forbidden',
                'backend.middleware.upload.not.image' : 'Please upload an image file',
                'backend.middleware.upload.image.processing.error' : 'Error during image processing',

                'backend.common.internal.server.error' : 'Internal server error',

                //navbar
                'navbar.home' : 'Home',
                'navbar.pong' : 'PingPong',
                'navbar.scoreboard' : 'Scoreboard',
                'navbar.chat' : 'Chat',
                'navbar.profile' : 'Profile',
                'navbar.admin' : 'Admin',
                'navbar.login' : 'Login',
                'navbar.register' : 'Register',

                //HomePage
                'homepage.home' : 'Welcome to our transcendence',

                //types
                'types.connexion.email' : 'Invalid email',
                'types.connexion.mdp' : 'Invalid password',
                'types.min.3' : 'Cannot contain less than 3 characters',
                'types.max.24' : 'Cannot contain more than 24 characters',
                'types.allowed_chars' : 'Allowed characters: letters, numbers, - and _',
                'types.email' : 'Valid email required',
                'types.min.10' : 'Cannot contain less than 10 characters',
                'types.mdp.char' : 'Must contain lowercase, uppercase, number and special character',
                'types.mdp.allow' : 'Allowed special characters: !@#$%&*()_-+=',
                'types.inscription.mdp.similar' : 'Passwords must match',

                //Admin
                'admin.common.loading': 'Loading...',
                'admin.header.title': 'Admin area',
                'admin.header.subtitle': 'Manage user accounts and permissions.',
                'admin.create.title': 'Create a user',
                'admin.create.subtitle': 'Fill in the information below to add a new account.',
                'admin.searchPlaceholder': 'Search by username, email or id',
                'admin.list.usersCount': 'Users ({{count}})',
                'admin.list.page': 'Page {{page}}/{{totalPages}}',
                'admin.emptyState': 'Select a user from the list to view details.',
                'admin.form.username': 'Username',
                'admin.form.email': 'Email',
                'admin.form.password': 'Password',
                'admin.form.newPassword': 'New password',
                'admin.form.passwordPlaceholder': 'Leave blank to keep current password',
                'admin.form.avatar': 'Avatar',
                'admin.role.title': 'User role',
                'admin.delete.title': 'Danger zone',
                'admin.delete.confirmMessage': 'Delete {{username}}? This action cannot be undone.',
                'admin.actions.search': 'Search',
                'admin.actions.refresh': 'Refresh',
                'admin.actions.previous': 'Previous',
                'admin.actions.next': 'Next',
                'admin.actions.createUser': 'Create user',
                'admin.actions.saveChanges': 'Save changes',
                'admin.actions.updateRole': 'Update role',
                'admin.actions.deleteUser': 'Delete this user',
                'admin.actions.confirm': 'Confirm',
                'admin.actions.cancel': 'Cancel',
                'admin.sort.createdAt': 'Creation date',
                'admin.sort.username': 'Username',
                'admin.sort.email': 'Email',
                'admin.sort.role': 'Role',
                'admin.sort.status': 'Status',
                'admin.sort.desc': 'DESC',
                'admin.sort.asc': 'ASC',
                'admin.roles.USER': 'User',
                'admin.roles.ADMIN': 'Administrator',
                'admin.status.online': 'ONLINE',
                'admin.status.offline': 'OFFLINE',
                'admin.editor.title': 'Editing {{username}}',
                'admin.feedback.loadError': 'Failed to load users',
                'admin.feedback.unexpectedLoadError': 'Unexpected error while loading users',
                'admin.feedback.createSuccess': 'User created successfully',
                'admin.feedback.createError': 'Failed to create user',
                'admin.feedback.unexpectedCreateError': 'Unexpected error while creating user',
                'admin.feedback.updateSuccess': 'User updated successfully',
                'admin.feedback.updateError': 'Failed to update user',
                'admin.feedback.unexpectedUpdateError': 'Unexpected error while updating user',
                'admin.feedback.roleUpdateSuccess': 'Role updated successfully',
                'admin.feedback.roleUpdateError': 'Failed to update role',
                'admin.feedback.unexpectedRoleUpdateError': 'Unexpected error while updating role',
                'admin.feedback.deleteSuccess': 'User deleted successfully',
                'admin.feedback.deleteError': 'Failed to delete user',
                'admin.feedback.unexpectedDeleteError': 'Unexpected error while deleting user',
                'admin.validation.invalidEmail': 'Invalid email',
                'admin.validation.usernameMin': 'Must contain at least 3 characters',
                'admin.validation.usernameMax': 'Must contain at most 24 characters',
                'admin.validation.usernamePattern': 'Allowed characters: letters, numbers, - and _',
                'admin.validation.passwordMin': 'Must contain at least 8 characters',
                'admin.validation.passwordPattern': 'Must include lowercase, uppercase, number and special character',
                'admin.validation.passwordSpecialChars': 'Allowed special characters: !@#$%&*()_-+=',
                'admin.validation.string': 'Invalid input: expected string, received undefined',
                
                //profile
                'profile.modifier' : 'Update',
                'profile.deconnecion' : 'logout',
                'profile.datecreate' : 'Creation date',
                'profile.actuelmdp' : 'Current password',
                'profile.newmdp' : 'New password',
                'profile.save' : 'Save',
                'profile.annule' : 'Cancel',
                'profile.delete' : 'Delete friend',
                'profile.add' : 'Add to Friend',
                'profile.pending' : 'Pending request',
                'profile.notification' : 'Notifications',
                'profile.newMessage' : 'New messages',
                'profile.friendRequest' : 'Friend requests',
                'profile.search' : 'Search',

                'profile.opponent' : 'Opponent',
                'profile.result' : 'Result',
                'profile.score' : 'Score',
                'profile.time' : 'Time',
                'profile.date' : 'Date',
            
                'profile.err.data' : 'Username or email already in use',
                'profile.err.wrongPassword' : 'Password does not match current password',
                'profile.err.avatar' : 'Error loading image',

                //chat
                'chat.send' : 'Send',
                'chat.yourMsg' : 'Your message',
                'chat.longMsg' : 'Your message is too long',
            }
        },
        es : {
            translation: {
                //Backend response
                'backend.admin.incorect.query.params' : 'Parámetros de consulta incorrectos',
                'backend.admin.invalid.page.size' : 'Valores de pagina y tamano invalidos',
                'backend.admin.invalid.sorting.params' : 'Parametros de ordenacion invalidos',
                'backend.admin.invalid.user.id' : 'Identificador de usuario invalido',
                'backend.admin.user.not.found' : 'Usuario no encontrado',
                'backend.admin.delete.self.forbidden' : 'No puedes eliminar tu propia cuenta',
                'backend.admin.delete.success' : 'Usuario eliminado correctamente',
                'backend.admin.change.own.role.forbidden' : 'No puedes cambiar tu propio rol',
                'backend.admin.role.required' : 'El rol es obligatorio',

                'backend.auth.duplicate.user' : 'Ya existe un usuario con ese email o nombre',
                'backend.auth.invalid.credentials' : 'Credenciales incorrectas',
                'backend.auth.logout.success' : 'Sesion cerrada correctamente',
                'backend.auth.no.user.after.authentication' : 'No se encontro usuario tras la autenticacion',
                'backend.auth.no.valid.token' : 'Token no valido',
                'backend.auth.token.missing' : 'Acceso denegado: falta el token',
                'backend.auth.token.invalid.or.expired' : 'Token invalido o expirado',
                'backend.auth.user.not.found' : 'Usuario no encontrado',
                'backend.auth.server.error' : 'Error del servidor durante la autenticacion',
                'backend.auth.refresh.token.invalid' : 'Refresh token invalido',
                'backend.auth.refresh.token.revoked' : 'Refresh token revocado',

                'backend.profile.no.user.after.authentication' : 'No se encontro usuario tras la autenticacion',
                'backend.profile.invalid.user.id' : 'Identificador de usuario invalido',
                'backend.profile.user.not.found' : 'Usuario no encontrado',
                'backend.profile.incorrect.credentials' : 'Credenciales incorrectas',
                'backend.profile.password.updated' : 'Contrasena actualizada correctamente',
                'backend.profile.no.file.uploaded' : 'No se subio ningun archivo',
                'backend.profile.avatar.uploaded' : 'Avatar subido correctamente',
                'backend.profile.search.query.too.short' : 'La busqueda debe tener al menos 2 caracteres',

                'backend.friends.no.user.after.authentication' : 'No se encontro usuario tras la autenticacion',
                'backend.friends.cannot.add.yourself' : 'No puedes agregarte a ti mismo',
                'backend.friends.already.friends' : 'Ya son amigos',
                'backend.friends.request.already.pending' : 'Ya hay una solicitud pendiente',
                'backend.friends.blocked.by.you' : 'Has bloqueado a este usuario',
                'backend.friends.blocked.you' : 'Este usuario te ha bloqueado',
                'backend.friends.unable.to.send.request' : 'No se pudo enviar la solicitud',
                'backend.friends.invalid.request.id' : 'Identificador de solicitud invalido',
                'backend.friends.request.not.found' : 'Solicitud de amistad no encontrada',
                'backend.friends.not.authorized' : 'No autorizado',
                'backend.friends.internal.error' : 'Error interno',
                'backend.friends.only.receiver.can.accept' : 'Solo el receptor puede aceptar',
                'backend.friends.only.receiver.can.reject' : 'Solo el receptor puede rechazar',
                'backend.friends.only.sender.can.cancel' : 'Solo el emisor puede cancelar',
                'backend.friends.request.not.pending' : 'La solicitud no esta pendiente',
                'backend.friends.invalid.action' : 'Accion invalida',
                'backend.friends.not.friends' : 'No son amigos',
                'backend.friends.unfriended' : 'Amistad eliminada',

                'backend.middleware.role.unauthorized' : 'No autenticado',
                'backend.middleware.role.forbidden' : 'Acceso prohibido',
                'backend.middleware.upload.not.image' : 'Debes subir un archivo de imagen',
                'backend.middleware.upload.image.processing.error' : 'Error al procesar la imagen',

                'backend.common.internal.server.error' : 'Error interno del servidor',

                //navbar
                'navbar.home' : 'Inicio',
                'navbar.pong' : 'PingPong',
                'navbar.scoreboard' : 'Tabla de puntuaciones',
                'navbar.chat' : 'Chat',
                'navbar.profile' : 'Perfil',
                'navbar.admin' : 'Admin',
                'navbar.login' : 'Iniciar sesion',
                'navbar.register' : 'Registarse',

                //HomePage
                'homepage.home' : 'Bienvenido a nuestra transcendence',

                //types
                'types.connexion.email' : 'Email invalido',
                'types.connexion.mdp' : 'Contraseña invalida',
                'types.min.3' : 'No puede contener menos de 3 caracteres',
                'types.max.24' : 'No puede contener mas de 24 caracteres',
                'types.allowed_chars' : 'Caracteres permitidos: letras, numeros, - y _',
                'types.email' : 'Se requiere un email valido',
                'types.min.10' : 'No puede contener menos de 10 caracteres',
                'types.mdp.char' : 'Debe contener minuscula, mayuscula, numero y caracter especial',
                'types.mdp.allow' : 'Caracteres especiales permitidos: !@#$%&*()_-+=',
                'types.inscription.mdp.similar' : 'Las contraseñas deben coincidir',

                //Admin
                'admin.common.loading': 'Cargando...',
                'admin.header.title': 'Espacio de administracion',
                'admin.header.subtitle': 'Gestion de cuentas de usuario y permisos.',
                'admin.create.title': 'Crear un usuario',
                'admin.create.subtitle': 'Completa la informacion de abajo para agregar una nueva cuenta.',
                'admin.searchPlaceholder': 'Buscar por nombre de usuario, email o id',
                'admin.list.usersCount': 'Usuarios ({{count}})',
                'admin.list.page': 'Pagina {{page}}/{{totalPages}}',
                'admin.emptyState': 'Selecciona un usuario de la lista para ver los detalles.',
                'admin.form.username': 'Nombre de usuario',
                'admin.form.email': 'Email',
                'admin.form.password': 'Contrasena',
                'admin.form.newPassword': 'Nueva contrasena',
                'admin.form.passwordPlaceholder': 'Dejalo vacio para no cambiarla',
                'admin.form.avatar': 'Avatar',
                'admin.role.title': 'Rol del usuario',
                'admin.delete.title': 'Zona peligrosa',
                'admin.delete.confirmMessage': 'Eliminar a {{username}}? Esta accion es irreversible.',
                'admin.actions.search': 'Buscar',
                'admin.actions.refresh': 'Actualizar',
                'admin.actions.previous': 'Anterior',
                'admin.actions.next': 'Siguiente',
                'admin.actions.createUser': 'Crear usuario',
                'admin.actions.saveChanges': 'Guardar cambios',
                'admin.actions.updateRole': 'Actualizar rol',
                'admin.actions.deleteUser': 'Eliminar este usuario',
                'admin.actions.confirm': 'Confirmar',
                'admin.actions.cancel': 'Cancelar',
                'admin.sort.createdAt': 'Fecha de creacion',
                'admin.sort.username': 'Nombre de usuario',
                'admin.sort.email': 'Email',
                'admin.sort.role': 'Rol',
                'admin.sort.status': 'Estado',
                'admin.sort.desc': 'DESC',
                'admin.sort.asc': 'ASC',
                'admin.roles.USER': 'Usuario',
                'admin.roles.ADMIN': 'Administrador',
                'admin.status.online': 'EN LINEA',
                'admin.status.offline': 'DESCONECTADO',
                'admin.editor.title': 'Edicion de {{username}}',
                'admin.feedback.loadError': 'Error al cargar los usuarios',
                'admin.feedback.unexpectedLoadError': 'Error inesperado al cargar los usuarios',
                'admin.feedback.createSuccess': 'Usuario creado correctamente',
                'admin.feedback.createError': 'No se pudo crear el usuario',
                'admin.feedback.unexpectedCreateError': 'Error inesperado al crear el usuario',
                'admin.feedback.updateSuccess': 'Usuario actualizado correctamente',
                'admin.feedback.updateError': 'No se pudo actualizar el usuario',
                'admin.feedback.unexpectedUpdateError': 'Error inesperado al actualizar el usuario',
                'admin.feedback.roleUpdateSuccess': 'Rol actualizado correctamente',
                'admin.feedback.roleUpdateError': 'No se pudo actualizar el rol',
                'admin.feedback.unexpectedRoleUpdateError': 'Error inesperado al actualizar el rol',
                'admin.feedback.deleteSuccess': 'Usuario eliminado correctamente',
                'admin.feedback.deleteError': 'No se pudo eliminar el usuario',
                'admin.feedback.unexpectedDeleteError': 'Error inesperado al eliminar el usuario',
                'admin.validation.invalidEmail': 'Email invalido',
                'admin.validation.usernameMin': 'Debe contener al menos 3 caracteres',
                'admin.validation.usernameMax': 'Debe contener como maximo 24 caracteres',
                'admin.validation.usernamePattern': 'Caracteres permitidos: letras, numeros, - y _',
                'admin.validation.passwordMin': 'Debe contener al menos 8 caracteres',
                'admin.validation.passwordPattern': 'Debe incluir minuscula, mayuscula, numero y caracter especial',
                'admin.validation.passwordSpecialChars': 'Caracteres especiales permitidos: !@#$%&*()_-+=',
                'admin.validation.string': 'Entrada no válida: se esperaba una cadena, se recibió undefined.',
                
                //profile
                'profile.modifier' : 'Modificar',
                'profile.deconnecion' : 'Desconexión',
                'profile.datecreate' : 'Fecha de creacion',
                'profile.actuelmdp' : 'Contraseña actual',
                'profile.newmdp' : 'Nueva contraseña',
                'profile.save' : 'Guardar',
                'profile.annule' : 'Cancelar',
                'profile.delete' : 'Eliminar el amigo',
                'profile.add' : 'Agregar como amigo',
                'profile.pending' : 'Solicitud pendiente',
                'profile.notification' : 'Notificaciones',
                'profile.newMessage' : 'Nuevos mensajes',
                'profile.friendRequest' : 'Solicitudes de amistad',
                'profile.search' : 'Buscar',

                'profile.opponent' : 'Oponente',
                'profile.result' : 'Resultado',
                'profile.score' : 'Puntuaciones',
                'profile.time' : 'Duración',
                'profile.date' : 'Fecha',
            
                'profile.err.data' : 'Nombre de usuario o correo electrónico ya en uso',
                'profile.err.wrongPassword' : 'La contraseña no coincide con la contraseña actual',
                'profile.err.avatar' : 'Error al cargen la imagen',

                //chat
                'chat.send' : 'Enviar',
                'chat.yourMsg' : 'Tu mensaje',
                'chat.longMsg' : 'Tu mensaje es dmasiado largo',
            }
        },

        ar : {
            translation: {
                //Backend response
                'backend.admin.incorect.query.params' : 'معلمات الاستعلام غير صحيحة',
                'backend.admin.invalid.page.size' : 'قيم الصفحة والحجم غير صالحة',
                'backend.admin.invalid.sorting.params' : 'معلمات فرز غير صالحة',
                'backend.admin.invalid.user.id' : 'معرف مستخدم غير صالح',
                'backend.admin.user.not.found' : 'لم يتم العثور على المستخدم',
                'backend.admin.delete.self.forbidden' : 'لا يمكنك حذف حسابك الخاص',
                'backend.admin.delete.success' : 'تم حذف المستخدم بنجاح',
                'backend.admin.change.own.role.forbidden' : 'لا يمكنك تغيير دورك الخاص',
                'backend.admin.role.required' : 'الدور مطلوب',

                'backend.auth.duplicate.user' : 'يوجد بالفعل مستخدم بهذا البريد الإلكتروني أو الاسم.',
                'backend.auth.invalid.credentials' : 'بيانات اعتماد غير صحيحة',
                'backend.auth.logout.success' : 'تم إغلاق الجلسة بشكل صحيح',
                'backend.auth.no.user.after.authentication' : 'لم يتم العثور على أي مستخدم بعد المصادقة',
                'backend.auth.no.valid.token' : 'رمز غير صالح',
                'backend.auth.token.missing' : 'تم رفض الوصول: الرمز المميز مفقود',
                'backend.auth.token.invalid.or.expired' : 'رمز غير صالح أو منتهي الصلاحية',
                'backend.auth.user.not.found' : 'لم يتم العثور على المستخدم',
                'backend.auth.server.error' : 'حدث خطأ في الخادم أثناء المصادقة',
                'backend.auth.refresh.token.invalid' : 'تحديث الرمز المميز غير الصالح',
                'backend.auth.refresh.token.revoked' : 'تم إلغاء رمز التحديث',

                'backend.profile.no.user.after.authentication' : 'لم يتم العثور على أي مستخدم بعد المصادقة',
                'backend.profile.invalid.user.id' : 'معرف مستخدم غير صالح',
                'backend.profile.user.not.found' : 'لم يتم العثور على المستخدم',
                'backend.profile.incorrect.credentials' : 'بيانات اعتماد غير صحيحة',
                'backend.profile.password.updated' : 'تم تحديث كلمة المرور بنجاح',
                'backend.profile.no.file.uploaded' : 'لم يتم تحميل أي ملف',
                'backend.profile.avatar.uploaded' : 'تم تحميل الصورة الرمزية بنجاح',
                'backend.profile.search.query.too.short' : 'يجب أن يتكون مصطلح البحث من حرفين على الأقل',

                'backend.friends.no.user.after.authentication' : 'لم يتم العثور على أي مستخدم بعد المصادقة',
                'backend.friends.cannot.add.yourself' : 'لا يمكنك إضافة نفسك',
                'backend.friends.already.friends' : 'إنهم أصدقاء بالفعل',
                'backend.friends.request.already.pending' : 'يوجد بالفعل طلب معلق.',
                'backend.friends.blocked.by.you' : 'لقد قمت بحظر هذا المستخدم',
                'backend.friends.blocked.you' : 'قام هذا المستخدم بحظرك',
                'backend.friends.unable.to.send.request' : 'تعذر إرسال الطلب.',
                'backend.friends.invalid.request.id' : 'معرّف الطلب غير صالح',
                'backend.friends.request.not.found' : 'لم يتم العثور على طلب الصداقة',
                'backend.friends.not.authorized' : 'غير مصرح به',
                'backend.friends.internal.error' : 'خطأ داخلي',
                'backend.friends.only.receiver.can.accept' : 'لا يمكن قبول ذلك إلا من قبل المستلم',
                'backend.friends.only.receiver.can.reject' : 'لا يمكن رفض الرفض إلا من قبل المتلقي',
                'backend.friends.only.sender.can.cancel' : 'لا يمكن إلغاء البطاقة إلا من قبل الجهة المصدرة.',
                'backend.friends.request.not.pending' : 'الطلب ليس قيد الانتظار.',
                'backend.friends.invalid.action' : 'إجراء غير صالح',
                'backend.friends.not.friends' : 'إنهم ليسوا أصدقاء',
                'backend.friends.unfriended' : 'تمت إزالة الصداقة',

                'backend.middleware.role.unauthorized' : 'لم تتم المصادقة عليها',
                'backend.middleware.role.forbidden' : 'ممنوع الوصول',
                'backend.middleware.upload.not.image' : 'يجب عليك تحميل ملف صورة',
                'backend.middleware.upload.image.processing.error' : 'خطأ في معالجة الصورة',

                'backend.common.internal.server.error' : 'خطأ في الخادم الداخلي',

                //navbar
                'navbar.home' : 'الرئيسية',
                'navbar.pong' : 'بونغ',
                'navbar.scoreboard' : 'النتائج',
                'navbar.chat' : 'الدردشة',
                'navbar.profile' : 'الملف الشخصي',
                // 'navbar.admin' : 'Admin',
                'navbar.admin' : 'Admin',
                'navbar.login' : 'تسجيل الدخول',
                'navbar.register' : 'التسجيل',

                //HomePage
                // 'homepage.home' : 'Bienvenido a nuestra transcendence',

                //types
                'types.connexion.email' : 'البريد الإلكتروني غير صالح',
                'types.connexion.mdp' : 'كلمة المرور غير صالحة',
                'types.min.3' : 'لا يمكن أن يحتوي على أقل من 3 أحرف',
                'types.max.24' : 'لا يمكن أن يحتوي على أكثر من 24 حرفاً',
                'types.allowed_chars' : 'الأحرف المسموح بها: حروف، أرقام، - و _',
                'types.email' : 'يرجى إدخال بريد إلكتروني صالح',
                'types.min.10' : 'لا يمكن أن يحتوي على أقل من 10 أحرف',
                'types.mdp.char' : 'يجب أن يحتوي على حرف صغير وكبير ورقم وحرف خاص',
                'types.mdp.allow' : 'الأحرف الخاصة المسموح بها: !@#$%&*()_-+=',
                'types.inscription.mdp.similar' : 'يجب أن تتطابق كلمتا المرور',

                //Admin
                'admin.common.loading': 'جارٍ التحميل...',
                'admin.header.title': 'لوحة الإدارة',
                'admin.header.subtitle': 'إدارة حسابات المستخدمين والصلاحيات.',
                'admin.create.title': 'إنشاء مستخدم',
                'admin.create.subtitle': 'أدخل المعلومات أدناه لإضافة حساب جديد.',
                'admin.searchPlaceholder': 'البحث بالاسم أو البريد الإلكتروني أو المعرف',
                'admin.list.usersCount': 'المستخدمون ({{count}})',
                'admin.list.page': 'الصفحة {{page}}/{{totalPages}}',
                'admin.emptyState': 'اختر مستخدماً من القائمة لعرض التفاصيل.',
                'admin.form.username': 'اسم المستخدم',
                'admin.form.email': 'البريد الإلكتروني',
                'admin.form.password': 'كلمة المرور',
                'admin.form.newPassword': 'كلمة المرور الجديدة',
                'admin.form.passwordPlaceholder': 'اتركه فارغاً للإبقاء على كلمة المرور الحالية',
                'admin.form.avatar': 'الصورة الشخصية',
                'admin.role.title': 'دور المستخدم',
                'admin.delete.title': 'منطقة خطرة',
                'admin.delete.confirmMessage': 'حذف {{username}}؟ هذا الإجراء لا يمكن التراجع عنه.',
                'admin.actions.search': 'بحث',
                'admin.actions.refresh': 'تحديث',
                'admin.actions.previous': 'السابق',
                'admin.actions.next': 'التالي',
                'admin.actions.createUser': 'إنشاء المستخدم',
                'admin.actions.saveChanges': 'حفظ التغييرات',
                'admin.actions.updateRole': 'تحديث الدور',
                'admin.actions.deleteUser': 'حذف هذا المستخدم',
                'admin.actions.confirm': 'تأكيد',
                'admin.actions.cancel': 'إلغاء',
                'admin.sort.createdAt': 'تاريخ الإنشاء',
                'admin.sort.username': 'اسم المستخدم',
                'admin.sort.email': 'البريد الإلكتروني',
                'admin.sort.role': 'الدور',
                'admin.sort.status': 'الحالة',
                'admin.sort.desc': 'تنازلي',
                'admin.sort.asc': 'تصاعدي',
                'admin.roles.USER': 'مستخدم',
                'admin.roles.ADMIN': 'مدير',
                'admin.status.online': 'متصل',
                'admin.status.offline': 'غير متصل',
                'admin.editor.title': 'تعديل {{username}}',
                'admin.feedback.loadError': 'خطأ في تحميل المستخدمين',
                'admin.feedback.unexpectedLoadError': 'خطأ غير متوقع أثناء تحميل المستخدمين',
                'admin.feedback.createSuccess': 'تم إنشاء المستخدم بنجاح',
                'admin.feedback.createError': 'فشل إنشاء المستخدم',
                'admin.feedback.unexpectedCreateError': 'خطأ غير متوقع أثناء إنشاء المستخدم',
                'admin.feedback.updateSuccess': 'تم تحديث المستخدم بنجاح',
                'admin.feedback.updateError': 'فشل تحديث المستخدم',
                'admin.feedback.unexpectedUpdateError': 'خطأ غير متوقع أثناء تحديث المستخدم',
                'admin.feedback.roleUpdateSuccess': 'تم تحديث الدور بنجاح',
                'admin.feedback.roleUpdateError': 'فشل تحديث الدور',
                'admin.feedback.unexpectedRoleUpdateError': 'خطأ غير متوقع أثناء تحديث الدور',
                'admin.feedback.deleteSuccess': 'تم حذف المستخدم بنجاح',
                'admin.feedback.deleteError': 'فشل حذف المستخدم',
                'admin.feedback.unexpectedDeleteError': 'خطأ غير متوقع أثناء حذف المستخدم',
                'admin.validation.invalidEmail': 'البريد الإلكتروني غير صالح',
                'admin.validation.usernameMin': 'لا يمكن أن يحتوي على أقل من 3 أحرف',
                'admin.validation.usernameMax': 'لا يمكن أن يحتوي على أكثر من 24 حرفاً',
                'admin.validation.usernamePattern': 'الأحرف المسموح بها: حروف، أرقام، - و _',
                'admin.validation.passwordMin': 'لا يمكن أن يحتوي على أقل من 8 أحرف',
                'admin.validation.passwordPattern': 'يجب أن يحتوي على حرف صغير وكبير ورقم وحرف خاص',
                'admin.validation.passwordSpecialChars': 'الأحرف الخاصة المسموح بها: !@#$%&*()_-+=',
                'admin.validation.string': 'إدخال غير صالح: كان من المتوقع سلسلة نصية، ولكن تم استلام قيمة غير معرفة.',
                
                // //profile
                'profile.modifier': 'تعديل',
                'profile.deconnecion': 'تسجيل الخروج',
                'profile.datecreate': 'تاريخ الإنشاء',
                'profile.actuelmdp': 'كلمة المرور الحالية',
                'profile.newmdp': 'كلمة المرور الجديدة',
                'profile.save': 'حفظ',
                'profile.annule': 'إلغاء',
                'profile.delete': 'إزالة الصديق',
                'profile.add': 'إضافة صديق',
                'profile.pending': 'طلب معلق',
                'profile.notification': 'الإشعارات',
                'profile.newMessage': 'رسائل جديدة',
                'profile.friendRequest': 'طلبات الصداقة',
                'profile.search': 'بحث',

                'profile.opponent': 'الخصم',
                'profile.result': 'النتيجة',
                'profile.score': 'النقاط',
                'profile.time': 'المدة',
                'profile.date': 'التاريخ',

                'profile.err.data': 'اسم المستخدم أو البريد الإلكتروني مستخدم بالفعل',
                'profile.err.wrongPassword': 'كلمة المرور لا تتطابق مع كلمة المرور الحالية',
                'profile.err.avatar': 'خطأ في تحميل الصورة',

                //chat
                'chat.send' : 'إرسال',
                'chat.yourMsg' : 'رسالتك',
                'chat.longMsg' : 'رسالتك طويلة جداً',
            }
        }
    }
});

export default i18n ;